version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=postgres://postgres:pass@db:5432/midtermdb
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=midtermdb
    ports:
      - "5433:5432"